services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/baby
      - PORT=3000
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - baby-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - baby-network

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - baby-network

volumes:
  mongo-data:

networks:
  baby-network:
    driver: bridge
